name: halo
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.11.4
  - matplotlib=3.7.1
  - pandas=2.0.3
  - scikit-learn
  - PyWavelets
  - ipykernel=6.25.0
  - numpy=1.25.2
  - pip=23.2.1
  - scipy=1.11.1
  - pygame=2.5.1
  - Pillow
  - pip:
      - python-osc
      - mne
